### ISSUE TITLE
如果返回给js json，默认还会包裹一层 code description？

### ISSUE THREAD

**Issue by palorotolo** [easilycoder/EasyBridge#2]
可以提供不包裹的方法吗？

**Comment by easilycoder** [comment]
包裹的code和description只是方便bridge内部去判别当前的js请求的结果和打印错误信息而已。实际上，前端接受到的请求结果是没有这两个字段内容的，而是客户端真实的传递的数据

**Comment by zhangdeyu** [comment]
为什么通过window.easyBridge.callHandler  callback中会拿到code和description呢  是使用的方式不对吗

**Comment by easilycoder** [comment]
@zhangdeyu 你是在哪里看到的code和description的信息的？目前bridge的脚本代码中会把整个从native传到bridge中的result打印出来，显示如下：
`{"code":0,"description":"success","result":"data send to js"}`
但是实际上，通过callback回调结果给业务的js层的时候，取到的值是result中的result字段内容，比如说：
`data send to js`
所以，不清楚你是不是把打一个打印当成是callback拿到的值了？你可以看一下在callback回调的时候打印一下拿到的result值，应该是不会有code和description的信息的

**Comment by zhangdeyu** [comment]
通过window.easyBridge.callHandler('xxx', params, function(data) {})

**Comment by zhangdeyu** [comment]
通过window.easyBridge.callHandler('xxx', params, function(data) {
console.log(res)
})

**Comment by zhangdeyu** [comment]
通过window.easyBridge.callHandler('xxx', params, function(data) {
console.log(data)
})

**Comment by easilycoder** [comment]
这里你拿到的data应该是不包含code和description信息的，你应该是把把bridge打印出的日志跟你自己打印的这个日志搞混淆了，你可以尝试在这个日志前加多一个标志字段，跟bridge的日志区分开来看一下，我后面会把bridge中多余的log输出给删掉

**Comment by easilycoder** [comment]
关于**EasyBridge**中，Java和JavaScript之间传递数据的说明：

* 所有从*JavaScirpt*中传递给*Java*的值，接收到的都是`String`字符串类型。业务层在实现处理接口`BridgeHandler`的时候，可以根据通讯协议文档确定要如何将String字符串进行转换，比如：

  ```kotlin
  override fun onCall(parameters: String?, callBack: ResultCallBack?) {
  	// if the parameters represent a json string,you can change it to the target object ,maybe using gson
  }
  ```

* 所有从Java中传递给JavaScirpt中的值，在JavaScirpt中接收到的就是所传递的值。比如：

  ```kotlin
  override fun onCall(parameters: String?, callBack: ResultCallBack?) {
  	val user = User("userName", 13, "Hangzhou")
      callBack?.onResult(user)
      // in JavaScirpt may recevie a dictionary object like:{address:"Hangzhou",age:13,name:"userName"}
  }
  ```

* 在**EasyBridge**中会先把`ResultCallBack`传递回来的结果封装成一个`CallBackMessage`对象，这个对象的定义如下：

  ```java
  final class CallBackMessage {
  	private int code;
      private String description;
      // the real result data from handler,and real result data may passed to JavaScirpt
      private Object result;
  }
  ```

  这个封装的作用仅是用于**EasyBridge**内部处理不同状态的调用结果，并且能够正确打印出错误信息，但是对接入的业务层是完全透明的，除了**配置混淆规则**之外，这个类对业务层是完全无感知的。在JavaScirpt的回调当中也仅仅只会拿到当中的result字段（也就是我们一开始从Java中回传的结果值）。
